# permissions for end users to view cronexecutioncleaners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cronexecutioncleaner-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cron-execution-cleaner
    app.kubernetes.io/part-of: cron-execution-cleaner
    app.kubernetes.io/managed-by: kustomize
  name: cronexecutioncleaner-viewer-role
rules:
- apiGroups:
  - lifecycle.github.io
  resources:
  - cronexecutioncleaners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lifecycle.github.io
  resources:
  - cronexecutioncleaners/status
  verbs:
  - get
